
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.046800        0.039686
     time (cpu & wall) for ordering          =        0.181781        0.181781
     time (cpu & wall) for other matrix prep =        0.052220        0.051240
     time (cpu & wall) for value input       =        0.015600        0.018916
     time (cpu & wall) for matrix distrib.   =        0.062400        0.072553
     time (cpu & wall) for numeric factor    =        0.093601        0.087963
     computational rate (gflops) for factor  =        3.518752        3.744258
     time (cpu & wall) for numeric solve     =        0.015600        0.012397
     computational rate (gflops) for solve   =        1.082575        1.362239
     effective I/O rate (GB/sec) for solve   =        4.033227        5.075137

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       50.904 MB
  Solver Memory allocated on core    1       =       50.884 MB
  Total Solver Memory allocated by all cores =      101.787 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.021333
     time (cpu & wall) for matrix distrib.   =        0.078000        0.074880
     time (cpu & wall) for numeric factor    =        0.078001        0.087208
     computational rate (gflops) for factor  =        4.222503        3.776682
     time (cpu & wall) for numeric solve     =        0.015600        0.012859
     computational rate (gflops) for solve   =        1.082575        1.313368
     effective I/O rate (GB/sec) for solve   =        4.033227        4.893067

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018074
     time (cpu & wall) for matrix distrib.   =        0.078000        0.075048
     time (cpu & wall) for numeric factor    =        0.078000        0.080980
     computational rate (gflops) for factor  =        4.222503        4.067159
     time (cpu & wall) for numeric solve     =        0.015600        0.012241
     computational rate (gflops) for solve   =        1.082575        1.379616
     effective I/O rate (GB/sec) for solve   =        4.033227        5.139879

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018396
     time (cpu & wall) for matrix distrib.   =        0.078000        0.071138
     time (cpu & wall) for numeric factor    =        0.078000        0.082261
     computational rate (gflops) for factor  =        4.222503        4.003798
     time (cpu & wall) for numeric solve     =        0.015600        0.013003
     computational rate (gflops) for solve   =        1.082575        1.298785
     effective I/O rate (GB/sec) for solve   =        4.033227        4.838736

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018381
     time (cpu & wall) for matrix distrib.   =        0.078000        0.079957
     time (cpu & wall) for numeric factor    =        0.093601        0.090445
     computational rate (gflops) for factor  =        3.518752        3.641502
     time (cpu & wall) for numeric solve     =        0.015600        0.013175
     computational rate (gflops) for solve   =        1.082575        1.281877
     effective I/O rate (GB/sec) for solve   =        4.033227        4.775741

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019068
     time (cpu & wall) for matrix distrib.   =        0.078000        0.070669
     time (cpu & wall) for numeric factor    =        0.078000        0.083771
     computational rate (gflops) for factor  =        4.222503        3.931659

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =            2086
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018376
     time (cpu & wall) for matrix distrib.   =        0.062400        0.071751
     time (cpu & wall) for numeric factor    =        0.109201        0.106388
     computational rate (gflops) for factor  =        3.016073        3.095814
     time (cpu & wall) for numeric solve     =        0.015600        0.014343
     computational rate (gflops) for solve   =        1.082575        1.177456
     effective I/O rate (GB/sec) for solve   =        4.033227        4.386713

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017686
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070598
     time (cpu & wall) for numeric factor    =        0.078000        0.081678
     computational rate (gflops) for factor  =        4.222503        4.032385

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017707
     time (cpu & wall) for matrix distrib.   =        0.078000        0.070937
     time (cpu & wall) for numeric factor    =        0.078001        0.079910
     computational rate (gflops) for factor  =        4.222503        4.121623
     time (cpu & wall) for numeric solve     =        0.015600        0.012628
     computational rate (gflops) for solve   =        1.082575        1.337384
     effective I/O rate (GB/sec) for solve   =        4.033227        4.982540

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017772
     time (cpu & wall) for matrix distrib.   =        0.078000        0.077603
     time (cpu & wall) for numeric factor    =        0.078000        0.085399
     computational rate (gflops) for factor  =        4.222503        3.856678
     time (cpu & wall) for numeric solve     =        0.015600        0.012640
     computational rate (gflops) for solve   =        1.082575        1.336138
     effective I/O rate (GB/sec) for solve   =        4.033227        4.977898

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019609
     time (cpu & wall) for matrix distrib.   =        0.078000        0.073405
     time (cpu & wall) for numeric factor    =        0.078000        0.080854
     computational rate (gflops) for factor  =        4.222503        4.073469
     time (cpu & wall) for numeric solve     =        0.015600        0.013935
     computational rate (gflops) for solve   =        1.082575        1.211935
     effective I/O rate (GB/sec) for solve   =        4.033227        4.515170

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018832
     time (cpu & wall) for matrix distrib.   =        0.078000        0.081689
     time (cpu & wall) for numeric factor    =        0.093601        0.083018
     computational rate (gflops) for factor  =        3.518752        3.967278
     time (cpu & wall) for numeric solve     =        0.015600        0.012376
     computational rate (gflops) for solve   =        1.082575        1.364549
     effective I/O rate (GB/sec) for solve   =        4.033227        5.083745

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              10
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.023867
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070984
     time (cpu & wall) for numeric factor    =        0.093601        0.085984
     computational rate (gflops) for factor  =        3.518752        3.830429
     time (cpu & wall) for numeric solve     =        0.015600        0.011925
     computational rate (gflops) for solve   =        1.082575        1.416162
     effective I/O rate (GB/sec) for solve   =        4.033227        5.276034

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018174
     time (cpu & wall) for matrix distrib.   =        0.078000        0.076434
     time (cpu & wall) for numeric factor    =        0.078001        0.084748
     computational rate (gflops) for factor  =        4.222503        3.886315
     time (cpu & wall) for numeric solve     =        0.015600        0.012212
     computational rate (gflops) for solve   =        1.082575        1.382971
     effective I/O rate (GB/sec) for solve   =        4.033227        5.152378

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018285
     time (cpu & wall) for matrix distrib.   =        0.078001        0.074650
     time (cpu & wall) for numeric factor    =        0.093601        0.085441
     computational rate (gflops) for factor  =        3.518752        3.854783
     time (cpu & wall) for numeric solve     =        0.015600        0.012161
     computational rate (gflops) for solve   =        1.082575        1.388677
     effective I/O rate (GB/sec) for solve   =        4.033227        5.173636

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.020311
     time (cpu & wall) for matrix distrib.   =        0.062400        0.069693
     time (cpu & wall) for numeric factor    =        0.093601        0.079693
     computational rate (gflops) for factor  =        3.518752        4.132850
     time (cpu & wall) for numeric solve     =        0.015600        0.012027
     computational rate (gflops) for solve   =        1.082575        1.404225
     effective I/O rate (GB/sec) for solve   =        4.033227        5.231561

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018843
     time (cpu & wall) for matrix distrib.   =        0.062400        0.071693
     time (cpu & wall) for numeric factor    =        0.093601        0.079314
     computational rate (gflops) for factor  =        3.518752        4.152593
     time (cpu & wall) for numeric solve     =        0.015600        0.012702
     computational rate (gflops) for solve   =        1.082575        1.329568
     effective I/O rate (GB/sec) for solve   =        4.033227        4.953419

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018615
     time (cpu & wall) for matrix distrib.   =        0.078001        0.077430
     time (cpu & wall) for numeric factor    =        0.093601        0.088451
     computational rate (gflops) for factor  =        3.518752        3.723625
     time (cpu & wall) for numeric solve     =        0.015600        0.012360
     computational rate (gflops) for solve   =        1.082575        1.366358
     effective I/O rate (GB/sec) for solve   =        4.033227        5.090484

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018254
     time (cpu & wall) for matrix distrib.   =        0.078001        0.071696
     time (cpu & wall) for numeric factor    =        0.093601        0.091425
     computational rate (gflops) for factor  =        3.518752        3.602490
     time (cpu & wall) for numeric solve     =        0.015600        0.013696
     computational rate (gflops) for solve   =        1.082575        1.233093
     effective I/O rate (GB/sec) for solve   =        4.033227        4.593995

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019140
     time (cpu & wall) for matrix distrib.   =        0.078000        0.070186
     time (cpu & wall) for numeric factor    =        0.093601        0.092219
     computational rate (gflops) for factor  =        3.518752        3.571469
     time (cpu & wall) for numeric solve     =        0.015600        0.012982
     computational rate (gflops) for solve   =        1.082575        1.300885
     effective I/O rate (GB/sec) for solve   =        4.033227        4.846560

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017681
     time (cpu & wall) for matrix distrib.   =        0.062400        0.071160
     time (cpu & wall) for numeric factor    =        0.078000        0.081506
     computational rate (gflops) for factor  =        4.222503        4.040896

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             894
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.020208
     time (cpu & wall) for matrix distrib.   =        0.078001        0.077512
     time (cpu & wall) for numeric factor    =        0.093601        0.093901
     computational rate (gflops) for factor  =        3.518752        3.507480
     time (cpu & wall) for numeric solve     =        0.015600        0.012896
     computational rate (gflops) for solve   =        1.082575        1.309562
     effective I/O rate (GB/sec) for solve   =        4.033227        4.878886

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =            2272
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.025870
     time (cpu & wall) for matrix distrib.   =        0.078001        0.074463
     time (cpu & wall) for numeric factor    =        0.093601        0.097156
     computational rate (gflops) for factor  =        3.518752        3.389996
     time (cpu & wall) for numeric solve     =        0.015600        0.013433
     computational rate (gflops) for solve   =        1.082575        1.257251
     effective I/O rate (GB/sec) for solve   =        4.033227        4.683998

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.019290
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070401
     time (cpu & wall) for numeric factor    =        0.093601        0.083161
     computational rate (gflops) for factor  =        3.518752        3.960488
     time (cpu & wall) for numeric solve     =        0.015600        0.011572
     computational rate (gflops) for solve   =        1.082575        1.459395
     effective I/O rate (GB/sec) for solve   =        4.033227        5.437102

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018183
     time (cpu & wall) for matrix distrib.   =        0.078000        0.070870
     time (cpu & wall) for numeric factor    =        0.078001        0.080379
     computational rate (gflops) for factor  =        4.222503        4.097548
     time (cpu & wall) for numeric solve     =        0.015600        0.013492
     computational rate (gflops) for solve   =        1.082575        1.251717
     effective I/O rate (GB/sec) for solve   =        4.033227        4.663379

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018406
     time (cpu & wall) for matrix distrib.   =        0.062400        0.074694
     time (cpu & wall) for numeric factor    =        0.093601        0.087710
     computational rate (gflops) for factor  =        3.518752        3.755055
     time (cpu & wall) for numeric solve     =        0.015600        0.012104
     computational rate (gflops) for solve   =        1.082575        1.395315
     effective I/O rate (GB/sec) for solve   =        4.033227        5.198366

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018315
     time (cpu & wall) for matrix distrib.   =        0.078001        0.077718
     time (cpu & wall) for numeric factor    =        0.078000        0.086469
     computational rate (gflops) for factor  =        4.222503        3.808973
     time (cpu & wall) for numeric solve     =        0.015600        0.012062
     computational rate (gflops) for solve   =        1.082575        1.400112
     effective I/O rate (GB/sec) for solve   =        4.033227        5.216239

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018349
     time (cpu & wall) for matrix distrib.   =        0.078001        0.070815
     time (cpu & wall) for numeric factor    =        0.078000        0.081134
     computational rate (gflops) for factor  =        4.222503        4.059408
     time (cpu & wall) for numeric solve     =        0.015600        0.011976
     computational rate (gflops) for solve   =        1.082575        1.410168
     effective I/O rate (GB/sec) for solve   =        4.033227        5.253703

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             161
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019196
     time (cpu & wall) for matrix distrib.   =        0.062400        0.072140
     time (cpu & wall) for numeric factor    =        0.093601        0.091387
     computational rate (gflops) for factor  =        3.518752        3.603984
     time (cpu & wall) for numeric solve     =        0.015600        0.012091
     computational rate (gflops) for solve   =        1.082575        1.396733
     effective I/O rate (GB/sec) for solve   =        4.033227        5.203649

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018189
     time (cpu & wall) for matrix distrib.   =        0.078001        0.076568
     time (cpu & wall) for numeric factor    =        0.078001        0.082563
     computational rate (gflops) for factor  =        4.222503        3.989174
     time (cpu & wall) for numeric solve     =        0.015600        0.012237
     computational rate (gflops) for solve   =        1.082575        1.380136
     effective I/O rate (GB/sec) for solve   =        4.033227        5.141815

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018317
     time (cpu & wall) for matrix distrib.   =        0.093601        0.084743
     time (cpu & wall) for numeric factor    =        0.078000        0.085784
     computational rate (gflops) for factor  =        4.222503        3.839368
     time (cpu & wall) for numeric solve     =        0.015600        0.012539
     computational rate (gflops) for solve   =        1.082575        1.346886
     effective I/O rate (GB/sec) for solve   =        4.033227        5.017941

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018955
     time (cpu & wall) for matrix distrib.   =        0.078001        0.073058
     time (cpu & wall) for numeric factor    =        0.093601        0.082413
     computational rate (gflops) for factor  =        3.518752        3.996436
     time (cpu & wall) for numeric solve     =        0.015600        0.012880
     computational rate (gflops) for solve   =        1.082575        1.311228
     effective I/O rate (GB/sec) for solve   =        4.033227        4.885092

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017450
     time (cpu & wall) for matrix distrib.   =        0.093601        0.081962
     time (cpu & wall) for numeric factor    =        0.078001        0.081270
     computational rate (gflops) for factor  =        4.222503        4.052631
     time (cpu & wall) for numeric solve     =        0.015600        0.012795
     computational rate (gflops) for solve   =        1.082575        1.319938
     effective I/O rate (GB/sec) for solve   =        4.033227        4.917542

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018996
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070475
     time (cpu & wall) for numeric factor    =        0.093601        0.089484
     computational rate (gflops) for factor  =        3.518752        3.680631
     time (cpu & wall) for numeric solve     =        0.015600        0.012681
     computational rate (gflops) for solve   =        1.082575        1.331769
     effective I/O rate (GB/sec) for solve   =        4.033227        4.961619

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018818
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070701
     time (cpu & wall) for numeric factor    =        0.093601        0.080490
     computational rate (gflops) for factor  =        3.518752        4.091918
     time (cpu & wall) for numeric solve     =        0.015600        0.015586
     computational rate (gflops) for solve   =        1.082575        1.083544
     effective I/O rate (GB/sec) for solve   =        4.033227        4.036836

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019011
     time (cpu & wall) for matrix distrib.   =        0.078000        0.070675
     time (cpu & wall) for numeric factor    =        0.078001        0.082737
     computational rate (gflops) for factor  =        4.222503        3.980756

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.024664
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070230
     time (cpu & wall) for numeric factor    =        0.093601        0.090571
     computational rate (gflops) for factor  =        3.518752        3.636438
     time (cpu & wall) for numeric solve     =        0.015600        0.012687
     computational rate (gflops) for solve   =        1.082575        1.331177
     effective I/O rate (GB/sec) for solve   =        4.033227        4.959416

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =             322
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.019545
     time (cpu & wall) for matrix distrib.   =        0.078000        0.075984
     time (cpu & wall) for numeric factor    =        0.078001        0.085431
     computational rate (gflops) for factor  =        4.222503        3.855222

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.019458
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070137
     time (cpu & wall) for numeric factor    =        0.093601        0.084753
     computational rate (gflops) for factor  =        3.518752        3.886080
     time (cpu & wall) for numeric solve     =        0.015600        0.011590
     computational rate (gflops) for solve   =        1.082575        1.457139
     effective I/O rate (GB/sec) for solve   =        4.033227        5.428695

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =              38
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018823
     time (cpu & wall) for matrix distrib.   =        0.078001        0.074148
     time (cpu & wall) for numeric factor    =        0.093601        0.090937
     computational rate (gflops) for factor  =        3.518752        3.621799
     time (cpu & wall) for numeric solve     =        0.015600        0.014203
     computational rate (gflops) for solve   =        1.082575        1.189086
     effective I/O rate (GB/sec) for solve   =        4.033227        4.430042

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018637
     time (cpu & wall) for matrix distrib.   =        0.062400        0.071805
     time (cpu & wall) for numeric factor    =        0.093601        0.081788
     computational rate (gflops) for factor  =        3.518752        4.026983
     time (cpu & wall) for numeric solve     =        0.015600        0.014262
     computational rate (gflops) for solve   =        1.082575        1.184177
     effective I/O rate (GB/sec) for solve   =        4.033227        4.411753

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018651
     time (cpu & wall) for matrix distrib.   =        0.062400        0.069969
     time (cpu & wall) for numeric factor    =        0.093601        0.086827
     computational rate (gflops) for factor  =        3.518752        3.793251
     time (cpu & wall) for numeric solve     =        0.015600        0.012959
     computational rate (gflops) for solve   =        1.082575        1.303198
     effective I/O rate (GB/sec) for solve   =        4.033227        4.855177

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018933
     time (cpu & wall) for matrix distrib.   =        0.062400        0.069022
     time (cpu & wall) for numeric factor    =        0.093601        0.088509
     computational rate (gflops) for factor  =        3.518752        3.721191
     time (cpu & wall) for numeric solve     =        0.015600        0.011474
     computational rate (gflops) for solve   =        1.082575        1.471899
     effective I/O rate (GB/sec) for solve   =        4.033227        5.483685

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     44

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.019851
     time (cpu & wall) for matrix distrib.   =        0.078001        0.072707
     time (cpu & wall) for numeric factor    =        0.078000        0.090003
     computational rate (gflops) for factor  =        4.222503        3.659400

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     45

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017853
     time (cpu & wall) for matrix distrib.   =        0.078001        0.079851
     time (cpu & wall) for numeric factor    =        0.078001        0.090005
     computational rate (gflops) for factor  =        4.222503        3.659338
     time (cpu & wall) for numeric solve     =        0.015600        0.012284
     computational rate (gflops) for solve   =        1.082575        1.374786
     effective I/O rate (GB/sec) for solve   =        4.033227        5.121884

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     46

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.020084
     time (cpu & wall) for matrix distrib.   =        0.078001        0.073820
     time (cpu & wall) for numeric factor    =        0.078001        0.082628
     computational rate (gflops) for factor  =        4.222503        3.986010
     time (cpu & wall) for numeric solve     =        0.015600        0.011974
     computational rate (gflops) for solve   =        1.082575        1.410470
     effective I/O rate (GB/sec) for solve   =        4.033227        5.254827

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019698
     time (cpu & wall) for matrix distrib.   =        0.062400        0.072620
     time (cpu & wall) for numeric factor    =        0.093601        0.086188
     computational rate (gflops) for factor  =        3.518752        3.821373
     time (cpu & wall) for numeric solve     =        0.015600        0.011631
     computational rate (gflops) for solve   =        1.082575        1.452007
     effective I/O rate (GB/sec) for solve   =        4.033227        5.409578

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     48

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.018342
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070506
     time (cpu & wall) for numeric factor    =        0.078001        0.080555
     computational rate (gflops) for factor  =        4.222503        4.088589
     time (cpu & wall) for numeric solve     =        0.015600        0.014878
     computational rate (gflops) for solve   =        1.082575        1.135152
     effective I/O rate (GB/sec) for solve   =        4.033227        4.229106

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018144
     time (cpu & wall) for matrix distrib.   =        0.062400        0.071068
     time (cpu & wall) for numeric factor    =        0.078000        0.080159
     computational rate (gflops) for factor  =        4.222503        4.108802

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     50

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.031200        0.022295
     time (cpu & wall) for matrix distrib.   =        0.062400        0.070090
     time (cpu & wall) for numeric factor    =        0.093601        0.081252
     computational rate (gflops) for factor  =        3.518752        4.053551
     time (cpu & wall) for numeric solve     =        0.015600        0.012318
     computational rate (gflops) for solve   =        1.082575        1.371072
     effective I/O rate (GB/sec) for solve   =        4.033227        5.108046

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     51

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.021154
     time (cpu & wall) for matrix distrib.   =        0.078001        0.071690
     time (cpu & wall) for numeric factor    =        0.093601        0.084429
     computational rate (gflops) for factor  =        3.518752        3.900997
     time (cpu & wall) for numeric solve     =        0.015600        0.014638
     computational rate (gflops) for solve   =        1.082575        1.153693
     effective I/O rate (GB/sec) for solve   =        4.033227        4.298184

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     52

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.019024
     time (cpu & wall) for matrix distrib.   =        0.078001        0.071104
     time (cpu & wall) for numeric factor    =        0.078001        0.081083
     computational rate (gflops) for factor  =        4.222503        4.061997
     time (cpu & wall) for numeric solve     =        0.015600        0.013425
     computational rate (gflops) for solve   =        1.082575        1.258019
     effective I/O rate (GB/sec) for solve   =        4.033227        4.686856

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     53

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.017717
     time (cpu & wall) for matrix distrib.   =        0.078001        0.070181
     time (cpu & wall) for numeric factor    =        0.078000        0.081255
     computational rate (gflops) for factor  =        4.222503        4.053397
     time (cpu & wall) for numeric solve     =        0.015600        0.012153
     computational rate (gflops) for solve   =        1.082575        1.389613
     effective I/O rate (GB/sec) for solve   =        4.033227        5.177123

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     54

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               1
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.024179
     time (cpu & wall) for matrix distrib.   =        0.062400        0.073937
     time (cpu & wall) for numeric factor    =        0.093601        0.083994
     computational rate (gflops) for factor  =        3.518752        3.921186
     time (cpu & wall) for numeric solve     =        0.015600        0.011798
     computational rate (gflops) for solve   =        1.082575        1.431465
     effective I/O rate (GB/sec) for solve   =        4.033227        5.333046

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB





  Performance statistics for DSP solver: icalls =     55

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           63912
     no. of nonzeroes in lower triangle of a =          986176
     no. of nonzeroes in the factor l        =         5036772
     ratio of nonzeroes in factor (min/max)  =          0.9999
     number of super nodes                   =            3968
     maximum order of a front matrix         =             130
     maximum size of a front matrix          =            8515
     maximum size of a front trapezoid       =            7098
     no. of floating point ops for factor    =      3.2936D+08
     no. of floating point ops for solve     =      1.6888D+07
     ratio of flops for factor (min/max)     =          0.9993
     near zero pivot monitoring activated
     number of pivots adjusted               =               0
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.000000
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015600        0.018868
     time (cpu & wall) for matrix distrib.   =        0.062400        0.069757
     time (cpu & wall) for numeric factor    =        0.093601        0.094455
     computational rate (gflops) for factor  =        3.518752        3.486908
     time (cpu & wall) for numeric solve     =        0.015600        0.012628
     computational rate (gflops) for solve   =        1.082575        1.337330
     effective I/O rate (GB/sec) for solve   =        4.033227        4.982338

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0        393216.        3. MB        377165.        3. MB
                95-   1        393216.        3. MB        377088.        3. MB

                -------     ----------     --------     ----------     --------
                Totals:        786432.        6. MB        754253.        6. MB


  Solver Memory allocated on core    0       =       43.274 MB
  Solver Memory allocated on core    1       =       43.254 MB
  Total Solver Memory allocated by all cores =       86.528 MB

